---
title: "hw-01"
author: "Arturo Vargas (s2639101)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}    
knitr::opts_chunk$set(out.width = "100%")
```


------------------------------------------------------------------------------

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse)
library(lubridate)
```

```{r load-data, message=FALSE}
edibnb <- read_csv("data/edibnb.csv")
council <- read_csv("data/council_assessments.csv")
```

------------------------------------------------------------------------------


## EXERCISE 1

```{r hw1-ex1}
colSums(is.na(edibnb))


edibnb%>%
  arrange(desc(number_of_reviews)) %>%
  filter(review_scores_rating == 100)


```


_price, neighbourhood, bathrooms, bedrooms, beds, review_scores_rating all have NA entries. The place with most num of reviews and a review score of 100 has an id of 860170 _

------------------------------------------------------------------------------

## EXERCISE 2

```{r hw1-ex2}
nrow(filter(edibnb, neighbourhood  == "Old Town", price > 100))

prices_data <- filter(edibnb, neighbourhood == "Southside", accommodates >= 4)

minimum_price = min(prices_data$price)
maximum_price = max(prices_data$price)
mean_price = mean(prices_data$price)

minimum_price
maximum_price
mean_price



```


_494 places with a stay price of more than 100 at Old Town. Minimum, maximum, and average price are 10, 800 and 153.1368 respectively in Southside for places that accomodate 4 people_


------------------------------------------------------------------------------

## EXERCISE 3

```{r hw1-ex3}
edibnb %>%
  filter(neighbourhood == "Newington") %>%
  count(bathrooms)

edibnb %>%
  mutate(
         bathrooms = ceiling(bathrooms)) %>%
  filter(bathrooms > bedrooms)


```


_963 places with more bathrooms than bedrooms._



------------------------------------------------------------------------------

## EXERCISE 4

```{r hw1-ex4}
council %>%
  mutate(
    assessment_date = dmy(assessment_date)
  ) %>%
  filter(month(assessment_date) == 5)



right_join(edibnb, council, by = "id") %>%
 count(neighbourhood)
```


_296 properties where assessed in the month of may. The frequency table reveals that the council is not targeting neighbourhoods in Edinburgh equally as Leith particularly has over 10 times the amount of properties assessed as the next most developed neighbourhoods (Old Town). Moreover certain neighbourhoods have 30-40 properties assessed while others are in the 80-145 range thus demonstrating a disparity between the number of assesed properties between areas. Frequency of number of assesed properties within neighbourhoods gives us evidence of unequal targeting in neighbourhoods by the council however a more meaningful data summary would be comparing the proportion of properties reviewed by the council in each neighbourhood. We would do this by doing a left join of edibnb and council datasets to get the unreviewed properties and using the mutate function we would create a new table that takes in the right join table but divides each of the entries by the respective entry in the left join table using [row, "n"]._


------------------------------------------------------------------------------
